### ISSUE TITLE
Ensure min_buy_volume parameters are integer data types

### ISSUE THREAD

**Issue by hoffer49** [PTMagicians/PTMagic#106]
I was using OFFSETPERCENT for "DEFAULT_min_buy_volume" and "DEFAULT_DCA_min_buy_volume" and was trying to offset it by a decimal number but it was not working. I was wondering if "DEFAULT_min_buy_volume" and "DEFAULT_DCA_min_buy_volume" are integer data types? If not, would changing these to an integer data type allow PTM to use OFFSETPERCENT with decimal values?

**Comment by HojouFotytu** [comment]
Same problem as https://github.com/PTMagicians/PTMagic/issues/42

**Comment by HojouFotytu** [comment]
https://github.com/PTMagicians/PTMagic/pull/108
