### ISSUE TITLE
updating from 2.0.3 to most recent version

### ISSUE THREAD

**Issue by bartgrefte** [PTMagicians/PTMagic#114]
I haven't updated PT and PTM in a while, when it comes to PT I found out I can't update to 2.2.12 in one go, I have to update to 2.1.30 first.

Will I be running into the same when updating PTM 2.0.3 to the most recent version? Or do I only have to change some settings, the ones listed at https://github.com/PTMagicians/PTMagic/releases ... and it seems I have to update .Net.

**Comment by HojouFotytu** [comment]
Simple questions like this are better answered in the discord chat.  This is an place to post bugs and feature requests.  ;)

Nevertheless, you are correct -- after installing the latest release of PTM, you should only have to add any new settings, and update .net.
