### ISSUE TITLE
Global setting change triggered every raid for 1 hour

### ISSUE THREAD

**Issue by dkr940** [PTMagicians/PTMagic#115]
**Describe the bug**

I'm from the UK and on Sunday March 31st 2019 the clocks were changed from UTC to UTC + 01:00. Ever since that date if I make a change to one or more of the presets or settings.analyzer.json files, on every subsequent raid the log file shows "Global setting changed: Yes" and the PT config is changed on every raid. After 1 hour the global setting stops getting changed on every raid until the next change of the presets and/or settings.analyzer.json files, then the global setting is changed on every raid for another hour.

**To Reproduce**

Make a change to a preset file or settings.analyzer.json file on a server that is running on UTC +01:00 timezone (or BST) and confirm that the global settings is changed every raid for 1 hour.

**Expected behavior**

The global setting should be changed only once after a change to the presets, or settings.analyzer.json files.

**Screenshots**

A preset file was changed around 13:38 on 2019/04/08. No further changes made.

Log excerpt:

2019/04/08 13:33:07.699 INFO - + Global setting changed: No
2019/04/08 13:35:08.518 INFO - + Global setting changed: No
2019/04/08 13:37:07.835 INFO - + Global setting changed: No
2019/04/08 13:39:04.209 INFO - + Global setting changed: Yes
2019/04/08 13:39:11.543 INFO - + Global setting changed: Yes
2019/04/08 13:41:13.269 INFO - + Global setting changed: Yes
2019/04/08 13:43:09.648 INFO - + Global setting changed: Yes
2019/04/08 13:45:08.334 INFO - + Global setting changed: Yes
2019/04/08 13:47:08.636 INFO - + Global setting changed: Yes
2019/04/08 13:49:08.351 INFO - + Global setting changed: Yes
2019/04/08 13:51:08.991 INFO - + Global setting changed: Yes
2019/04/08 13:53:19.908 INFO - + Global setting changed: Yes
2019/04/08 13:55:22.275 INFO - + Global setting changed: Yes
2019/04/08 13:57:10.248 INFO - + Global setting changed: Yes
2019/04/08 13:59:08.340 INFO - + Global setting changed: Yes
2019/04/08 14:01:08.311 INFO - + Global setting changed: Yes
2019/04/08 14:03:09.895 INFO - + Global setting changed: Yes
2019/04/08 14:05:09.004 INFO - + Global setting changed: Yes
2019/04/08 14:07:08.639 INFO - + Global setting changed: Yes
2019/04/08 14:09:10.139 INFO - + Global setting changed: Yes
2019/04/08 14:11:08.429 INFO - + Global setting changed: Yes
2019/04/08 14:13:08.606 INFO - + Global setting changed: Yes
2019/04/08 14:15:08.655 INFO - + Global setting changed: Yes
2019/04/08 14:17:08.535 INFO - + Global setting changed: Yes
2019/04/08 14:19:09.326 INFO - + Global setting changed: Yes
2019/04/08 14:21:07.823 INFO - + Global setting changed: Yes
2019/04/08 14:23:08.858 INFO - + Global setting changed: Yes
2019/04/08 14:25:19.462 INFO - + Global setting changed: Yes
2019/04/08 14:27:09.094 INFO - + Global setting changed: Yes
2019/04/08 14:29:09.377 INFO - + Global setting changed: Yes
2019/04/08 14:31:14.819 INFO - + Global setting changed: Yes
2019/04/08 14:33:12.150 INFO - + Global setting changed: Yes
2019/04/08 14:35:12.080 INFO - + Global setting changed: Yes
2019/04/08 14:37:08.998 INFO - + Global setting changed: Yes
2019/04/08 14:39:09.796 INFO - + Global setting changed: Yes
2019/04/08 14:41:07.570 INFO - + Global setting changed: No
2019/04/08 14:43:07.526 INFO - + Global setting changed: No
2019/04/08 14:45:07.886 INFO - + Global setting changed: No

**Desktop (please complete the following information):**

PTMagic version 2.2.1
OS: MacOS 10.13

**Smartphone (please complete the following information):**

**Additional context**

**Comment by djbadders** [comment]
Found a file timestamp comparison that wasn't UTC; fixed and will be in next release.
