### ISSUE TITLE
Flexible DCA  

### ISSUE THREAD

**Issue by noto777** [PTMagicians/PTMagic#119]
use PTMagic to have one DCA buy strategy for the first X buys then switch to a different one after that?

HojouToday at 5:32 AM
At the moment no, however it might be possible to add something to the analyzer like "AllowedMarkets", for SMS settings -- eg., "DCACount"  to filter markets via an SMS based on a specified DCA count

**Comment by HojouFotytu** [comment]
This can now be done directly within Profit Trailer, using numbered strategies.

Eg., 
DCA_A_buy_strategy_1 = EMAGAIN
DCA_A_buy_strategy_2 = LOWBB
