### ISSUE TITLE
Graphs not showing up in V2.2.3

### ISSUE THREAD

**Issue by rbkuhn** [PTMagicians/PTMagic#133]
**Describe the bug**
The graphs on the dashboard page are not showing.

**To Reproduce**
When upgrading from V2.2.2 to V2.2.3, the graphs did not show up. The spaces for them to populate are there, but the graphs themselves are not showing up. I went back to V2.2.2 and the graphs were back, moving to V2.2.3 and they disappeared again.

**Expected behavior**
The graphs should be shown as in V2.2.2

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows 2016 Server]
 - Browser: Chrome, Firefox, Brave
 - Version:
Chrome - Version 74.0.3729.131 (Official Build) (64-bit)
Firefox - Version 66.0.5 (64-bit)
Brave - Version 0.63.55 Chromium: 74.0.3729.131 (Official Build) (64-bit)

**Additional context**
DotNet Hosting version = 2.2.0
DotNet SDK version = 2.2.101

**Comment by HojouFotytu** [comment]
My guess is that this is only occurring on windows 2016 server.  Need more feedback from anyone else having this same problem.

**Comment by eapiauhy** [comment]
Hi, 

my graph work on another machine 
not working for me: Poloniex, Bittrex.
Win 10 lastest version. 
Chrome: Versão 74.0.3729.131 (Versão oficial) 64 bits
DotNet Hosting version = 2.1.7 (updated to 2.2.4)
DotNet SDK version = 2.1.7 (updated to 2.2.4)

Working: Binance.
Win 7 pro
Chrome: Versão 74.0.3729.131 (Versão oficial) 64 bits
DotNet Hosting version = 2.1.7 (updated to 2.2.4)
DotNet SDK version = 2.1.7 (updated to 2.2.4)

**Comment by sorentorp** [comment]
I have the same problem. 

Is there any logs from the browser I can provide to help?

**Comment by HojouFotytu** [comment]
@sorentorp could you also share your OS, browser, and dotnet versions?

**Comment by sorentorp** [comment]
Server
Debian 4.9.0-8-amd64
PTMagic version: V2.2.3
Dotnet: 2.2.204
I'm only using Binance.

Client
Chrome: Version 75.0.3770.38 (Officiel version) beta (64-bit)
OS: Windows 10 and MacOSX (latest)

**Comment by HojouFotytu** [comment]
@sorentorp what's your discord handle?

**Comment by djbadders** [comment]
Can you upload your PTM Monitor log files as well please

**Comment by djbadders** [comment]
The only real reason for the graphs not showing up would be a failure to either get the data from the server or a browser issue rendering. Is there anything showing in the console logs on the browsers as well. Haven't been able to reproduce the issue so far.

**Comment by rbkuhn** [comment]
Attached is the console from my browser.
![PTM_console_error](https://user-images.githubusercontent.com/20474138/58787057-426fad00-85e9-11e9-8973-e00030207c3e.png)

**Comment by sorentorp** [comment]
This is from my browser
![image](https://user-images.githubusercontent.com/4117997/58790258-4b17b180-85f0-11e9-9506-b2fed9e46b1c.png)

**Comment by rbkuhn** [comment]
Problem still present in 2.2.4

**Comment by djbadders** [comment]
Ok thanks for confirming. Can you also look at your network log in your Chrome browsers debugger and look for the response for the request to DashboardBottom page please.

**Comment by rbkuhn** [comment]
Attached are some screenshots, I've also attached a text file that contains the output of the response. Is this what you needed?
[DashboardBottom_Response.txt](https://github.com/PTMagicians/PTMagic/files/3268855/DashboardBottom_Response.txt)
![Screenshot at 2019-06-08 21-09-14](https://user-images.githubusercontent.com/20474138/59151373-49a41a00-8a32-11e9-9ddc-a72c363b13a7.png)
![Screenshot at 2019-06-08 21-09-25](https://user-images.githubusercontent.com/20474138/59151374-4a3cb080-8a32-11e9-9eec-30ce799efbec.png)
![Screenshot at 2019-06-08 21-09-36](https://user-images.githubusercontent.com/20474138/59151375-4a3cb080-8a32-11e9-9ef0-b6e74613b680.png)

**Comment by djbadders** [comment]
Hmmm the response all looks good, but the browser is complaining of a bad parse... will need to think about this one. Anything showing in your log file for PTM Monitor or PTM?

**Comment by rbkuhn** [comment]
No, it looks normal. Looks like it did for V2.3.3

**Comment by djbadders** [comment]
I have just checked in a fix; the issue only affects certain locals where commas are used in the number formatting. Hopefully have a patch released soon.

**Comment by HojouFotytu** [comment]
@djbadders is the man.
