### ISSUE TITLE
Dashboard Sales show zero

### ISSUE THREAD

**Issue by HojouFotytu** [PTMagicians/PTMagic#152]
**Describe the bug**
Yesterday and Today on Dashboard show zero sales.  However Last 7Days and Last 30days are correct.  

A problem pulling data from the new PT APIv2?

Strangely, restarting the monitor fixes the problem.

**Screenshots**
![](https://cdn.discordapp.com/attachments/414916350444830732/634827602707742736/unknown.png)

**Comment by HojouFotytu** [comment]
Looks like a time-zone issue.    This is also using UTC time:
![image](https://user-images.githubusercontent.com/36724681/67136055-12553d80-f25c-11e9-9ec6-f78eb36120ae.png)

**Comment by djbadders** [comment]
PR #155 has a fix for this issue
