### ISSUE TITLE
Broken SMS tooltips

### ISSUE THREAD

**Issue by HojouFotytu** [PTMagicians/PTMagic#154]
Tooltips for SMS settings are broken throughout the monitor, on dashboard, marketanalyzer, etc

**Comment by HojouFotytu** [comment]
https://github.com/PTMagicians/PTMagic/pull/148/commits/377e443f6263797486076918dbc23bca41624233

??

**Comment by djbadders** [comment]
Are we talking about the tool tips for the strategies? On the latest code I'm not seeing any issues...
![image](https://user-images.githubusercontent.com/34887832/67141600-e0db7280-f259-11e9-8a43-d30256570455.png)

**Comment by HojouFotytu** [comment]
the SMS tooltip.  The orange triangle indicator next to pairs with SMS.

**Comment by HojouFotytu** [comment]
![image](https://user-images.githubusercontent.com/36724681/67143199-db0a7f00-f2a3-11e9-85fe-9e42b47132a9.png)

**Comment by djbadders** [comment]
Issue traced to the upgrading to Bootstrap 2.3.1 , I have regressed to 2.2.1 for now as this works.
