### ISSUE TITLE
Incorrect Buy Strats for non-DCA pairs

### ISSUE THREAD

**Issue by HojouFotytu** [PTMagicians/PTMagic#16]
In the Pairs/DCA list, (both Dashboard and Bag Analyzer), if a pair is not in DCA, the buy strats are incorrect.

If a pair is not in DCA, it should not list ANY buy strats at all, since it is not currently beings considered for a buy.

![Example](https://i.imgur.com/qC4sJFG.png)

**Comment by nnation** [comment]
What would the user interface look like? Would N/A be an appropriate label? Which would mean "Not Applicable" or would this column be removed completely?

**Comment by HojouFotytu** [comment]
The column can't be removed -- since both Pairs and DCA coins are in the same table.  I think N/A would be best...

**Comment by nnation** [comment]
Ok so I have come up with the fix. Check it out. 
![screenshot 2019-02-22 at 6 02 14 pm](https://user-images.githubusercontent.com/8162503/53276309-8db21f80-36cc-11e9-8d9a-06f88d428b20.png)

and 

![screenshot 2019-02-22 at 6 02 25 pm](https://user-images.githubusercontent.com/8162503/53276407-d8cc3280-36cc-11e9-9db8-a0df1f8bcaf5.png)

**Comment by HojouFotytu** [comment]
Great work - thanks!
