### ISSUE TITLE
"Freeze" column headings in "TREND OVERVIEW" of the Sales Analyzer

### ISSUE THREAD

**Issue by hoffer49** [PTMagicians/PTMagic#173]
Would it be possible to "freeze" the column headings in the "TREND OVERVIEW" in the Sales Analyzer so you can determine what market trend changes for coins lower on the list

**Comment by HojouFotytu** [comment]
![image](https://user-images.githubusercontent.com/36724681/68828674-df328c80-06e9-11ea-98fb-e2df7de726dc.png)
