### ISSUE TITLE
downlaoded PTM 2.4.1 installed as 2.4.0

### ISSUE THREAD

**Issue by Feddok** [PTMagicians/PTMagic#192]
I noticed there was an update. PTM v2.4.1
When I installed it it was v2.4.0 

![PTM 2 4 1  download](https://user-images.githubusercontent.com/41201062/72626946-effeb900-394b-11ea-9548-45fb3ecb9921.PNG)
![PTM 2 4 0](https://user-images.githubusercontent.com/41201062/72626950-f2611300-394b-11ea-9923-12809209938a.PNG)

**Comment by HojouFotytu** [comment]
Thanks.  It was fixed a few hours later.
