### ISSUE TITLE
Profit calculation not correct when loss occurs

### ISSUE THREAD

**Issue by Soeski** [PTMagicians/PTMagic#195]
When a loss occurs, PTMagic shows and handles it as profit making the stats useless. Using 2.4.3.
![ProfitLossError](https://user-images.githubusercontent.com/36672385/73607990-80303580-45bd-11ea-91f7-4d43c2bfe2b9.png)

**Comment by HojouFotytu** [comment]
Unfortunately I'm travelling for a few weeks, so it might take a while to fix this.  

But don't worry about your sales history, it's just pulling everything from PT.  So once the bug is fixed, PTM will show everything correctly.
