### ISSUE TITLE
Start up Error BinanceUS USDUSDT

### ISSUE THREAD

**Issue by Christophorio** [PTMagicians/PTMagic#203]
**Describe the bug**
I just upgraded from a couple versions back. I had to migrate to Binance.us and I am trading in USD, not USDT. So pairs.properties is set to USD and PT functions as expected. When I start PTMagic is where the problem lies.

When I change Pairs.properties from market = USD to market = USDT the error goes away. However, all of my pairs, buy and sell info does not display in PTMagic or PT.

**To Reproduce**
1. Use BinanceUS
2. Set  market = USD in default pairs. properties file
3. Start PTMagic
ERROR - Error whilst calling https://api.binance.us/api/v1/ticker/24hr?symbol=USDUSDT - {"code":-1121,"msg":"Invalid symbol."} 
2020/06/10 09:31:04.671 ERROR - Error whilst calling https://api.binance.us/api/v1/ticker/24hr?symbol=USDUSDT 
Error: Error whilst calling https://api.binance.us/api/v1/ticker/24hr?symbol=USDUSDT - {"code":-1121,"msg":"Invalid symbol."} 
2020/06/10 09:31:04.671 FATAL - Error whilst calling https://api.binance.us/api/v1/ticker/24hr?symbol=USDUSDT - {"code":-1121,"msg":"Invalid symbol."} System.Exception Error whilst calling https://api.binance.us/api/v1/ticker/24hr?symbol=USDUSDT - {"code":-1121,"msg":"Invalid symbol."}    at Core.MarketAnalyzer.BaseAnalyzer.GetJsonStringFromURL(String url, LogHelper log, ValueTuple`2[] headers) in g:\PTM Dev Bot\PTMagic Github Clone\PTMagic\Core\MarketAnalyzer\BaseAnalyzer.cs:line 69 at Core.MarketAnalyzer.BaseAnalyzer.GetSimpleJsonObjectFromURL(String url, LogHelper log, ValueTuple`2[] headers) in g:\PTM Dev Bot\PTMagic Github Clone\PTMagic\Core\MarketAnalyzer\BaseAnalyzer.cs:line 103  at Core.MarketAnalyzer.BinanceUS.GetMainCurrencyPrice(String mainMarket, PTMagicConfiguration systemConfiguration, LogHelper log) in g:\PTM Dev Bot\PTMagic Github Clone\PTMagic\Core\MarketAnalyzer\BinanceUS.cs:line 29

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox (but this is in the console)
 - Version 77.0.1

**Comment by HojouFotytu** [comment]
After some digging, it looks like this isn't a PTM issue.

Without even using PTM, I noticed that if I do NOT specify a trigger currency in PT, i get the error described above.

Even without any trigger settings, if your pairs file doesn't specify a market for "price_trigger_market", PT sees to default to USD, which causes the error.

Setting ANY market (other than USD) appears to solve this issue.

**Comment by HojouFotytu** [comment]
Even after adapting for the error in PT, PTM still generates a similar error.  PTM needs a fix to the BinanceUS analyzer to allow for USD as a base currency.

**From PTM discord:**
[5:39 AM] DrunkenTyger: ...PTMagic has the API link add +USDT. In "/Core/MarketAnalyzer/BinanceUS.cs" on line 26 there is the api link "string baseUrl = "https://api.binance.us/api/v1/ticker/24hr?symbol=" + mainMarket + "USDT";". That line translates to the broken "https://api.binance.us/api/v1/ticker/24hr?symbol=USDUSDT" with USD because of the "+ USDT"...
