### ISSUE TITLE
PTM Still needs a path for profit trailer 

### ISSUE THREAD

**Issue by Drunk-Octopus** [PTMagicians/PTMagic#219]
Why does PTM need to know the path of PT? I'd like to run PT on the PT VPS but as PTM needs the path this means it will not work. I thought PTM used API calls?

**Comment by Schneidoa** [comment]
I also want to run PTM on another server. I would love it if the feature is implemented.

**Comment by HojouFotytu** [comment]
This will be available with the next release.
