### ISSUE TITLE
Balance not showing correctly in PTM

### ISSUE THREAD

**Issue by MrSiNiSt3R** [PTMagicians/PTMagic#255]
**Describe the bug**
Running a live bot on Kali Linux Rolling, in PT the balance is set and showing, in PTM somehow the balance is not showing correctly, balance donut not showing, infinite balance and NaN prediction (see printscreens).

**Reproduce**
1. Install PT&PTM on Kali Linux Rolling
2. Run them all

**Expected behavior**
Donuts and balance showing as usual.

**Screenshots**
![1_PT_balance](https://user-images.githubusercontent.com/19706282/107621042-f302d080-6c55-11eb-9feb-daf50f176051.png)
![2_PTM_no_donut](https://user-images.githubusercontent.com/19706282/107621045-f39b6700-6c55-11eb-813e-08362e2f57bb.png)
![3_PTM_infinite_account_value](https://user-images.githubusercontent.com/19706282/107621046-f433fd80-6c55-11eb-937b-e5373ae159a8.png)
![4_PTM_NaN_balance_prediction](https://user-images.githubusercontent.com/19706282/107621047-f433fd80-6c55-11eb-8e26-9fabfc9e93c6.png)

**Laptop (Leonovo G50):**
 - OS: Kali Linux Rolling
 - Browser: Chrome
 - Version: Version 88.0.4324.150 (Official Build) (64-bit)

Feel free to ask for additional info!

**Comment by djbadders** [comment]
Looks like it can be caused when leverage is not in use but you have a pending pair; will get this resolved.
