### ISSUE TITLE
Pending Analyzer

### ISSUE THREAD

**Issue by hoffer49** [PTMagicians/PTMagic#27]
The addition of a "Pending Analyzer", similar to the "Bag Analyzer", might be useful.

**Comment by HojouFotytu** [comment]
How about just adding pending orders to the dashboard, and the bag analyzer page?

**Comment by hoffer49** [comment]
Yes, that would work!

Sent from Mail for Windows 10

**Comment by HojouFotytu** [comment]
After looking into this, it isn't possible.  

PTM only has access to the Profit Trailer data set, and PT doesn't keep track of pending orders at all -- the PT monitor just reads them directly from the exchange.

**Comment by HojouFotytu** [comment]
added with https://github.com/PTMagicians/PTMagic/pull/129
