### ISSUE TITLE
Default Properties file names on *Nix

### ISSUE THREAD

**Issue by Jthwaits** [PTMagicians/PTMagic#286]
**Describe the bug**
When performing the default installation on Linux, everything is fine except that *nix can't find the default config files. The files supplied in the folder "default_settings_for_PT_2.x" have the ".Properties" extension.

However, since *nix recognizes upper and lowercase files as different files entirely, PTM looks for ".properties" files upon launch where the default settings files are all "*.Properties". PTM therefore can't find the ".properties" files on the filesystem and aborts the launch.

**To Reproduce**
Nothing fancy, just the default installation of PTM, following the instructions and launching.

**Expected behavior**
PTM Launches into it's default state.

**Screenshots**
`root@DietPiRpi4:/home/dietpi/PTMagic/PTM_2.5.7/PTMagic# dotnet PTMagic.dll
[leaving out the unecessary part]
2021/03/13 16:28:58.409 INFO - ========== CHECKS FOR Profit Trailer COMPLETED! ==========
2021/03/13 16:28:58.409 INFO - No CoinMarketCap API KEY specified! You can't use CoinMarketCap in your settings.analyzer.json
2021/03/13 16:28:58.409 INFO - FreeCurrencyConverterApi KEY found
2021/03/13 16:28:58.442 INFO - Checking automated settings for presets...
2021/03/13 16:28:58.447 FATAL - Not able to find preset file PAIRS.properties for 'Default' System.Exception Not able to find preset file PAIRS.properties for 'Default'
2021/03/13 16:28:58.457 FATAL - Unhandled fatal exception occurred:  System.Exception Not able to find preset file PAIRS.properties for 'Default'    at Core.ProfitTrailer.SettingsFiles.CheckPresets(PTMagicConfiguration systemConfiguration, LogHelper log, Boolean forceCheck) in G:\PTM Dev Bot\PTMagic Github Clone\PTMagic\Core\ProfitTrailer\SettingsFiles.cs:line 131
   at Core.Main.PTMagic.StartProcess() in G:\PTM Dev Bot\PTMagic Github Clone\PTMagic\Core\Main\PTMagic.cs:line 565
   at PTMagic.Program.Main(String[] args) in G:\PTM Dev Bot\PTMagic Github Clone\PTMagic\PTMagic\Program.cs:line 31
Unhandled exception. System.Exception: Not able to find preset file PAIRS.properties for 'Default'
   at Core.ProfitTrailer.SettingsFiles.CheckPresets(PTMagicConfiguration systemConfiguration, LogHelper log, Boolean forceCheck) in G:\PTM Dev Bot\PTMagic Github Clone\PTMagic\Core\ProfitTrailer\SettingsFiles.cs:line 131
   at Core.Main.PTMagic.StartProcess() in G:\PTM Dev Bot\PTMagic Github Clone\PTMagic\Core\Main\PTMagic.cs:line 565
   at PTMagic.Program.Main(String[] args) in G:\PTM Dev Bot\PTMagic Github Clone\PTMagic\PTMagic\Program.cs:line 31
Aborted`

Note the line of interest: 
`2021/03/13 16:28:58.447 FATAL - Not able to find preset file PAIRS.properties for 'Default' System.Exception Not able to find preset file PAIRS.properties for 'Default
`

**Desktop (please complete the following information):**
 - OS: DietPi (Debian derivative)
 - Hardware: Raspberry Pi
 - Version: 2.5.7

**Additional context**
Renaming the default properties file should be a simple enough fix.

**Comment by HojouFotytu** [comment]
I just checked, and 2.5.7 settings files are named entirely in uppercase.
![image](https://user-images.githubusercontent.com/36724681/112413537-b7364d00-8d63-11eb-88b1-8751536f8161.png)

I don't use Linux so I'm not familiar with how the file system handles naming.   Is Linux changing the file names from all caps, to initial caps?

**Comment by HojouFotytu** [comment]
Added with Release 2.5.8
