### ISSUE TITLE
Ability to change TradingView link

### ISSUE THREAD

**Issue by pfakanator** [PTMagicians/PTMagic#301]
Us folks across the pond would like to have the lowest latency to market data.

Settings -> Monitor -> Link Platform to include TradingView US.

Considered forking and editing source but I'm a linux user and have no experience
setting up .NET cross compilers.

**Comment by HojouFotytu** [comment]
This is only used for the embedded chart, not market data.  Unless you are using a chart with 1 second candles the minor increase in latency is insignificant.

The US domain caused a refresh issue, so we switched to the UK domain.
