### ISSUE TITLE
No valid pairs found when using "enabled_pairs" list

### ISSUE THREAD

**Issue by HojouFotytu** [PTMagicians/PTMagic#305]
https://discord.com/channels/410746797649035266/414927200161366029/854375308060131350

PTM returns an error:
`No valid pairs found for main market 'USDT' in configured pars list`

when using PT standard "enabled_pairs = xxx, xxx, xxx..."  instead of "DEFAULT_enabled_pairs = xxx, xxx, xxx..."

**Comment by HojouFotytu** [comment]
I received no error when using:
`enabled_pairs = AAVE, BCH, BTC, DENT, DOT, ENJ, EOS, ETH, FIL, FTM, KNC, IOST, IOTA, LINK, LTC, NEO, OMG, SOL, THETA, TRX, XLM, XMR, XRP, XTZ, ZEC`

**Comment by vossen-adobe** [comment]
Effectively fresh PTM install with exchange=Binance with CMC api enabled, and Profit Trailer set for Kucoin. Platform in PTM analyzer set to coinmarketcap as well, but all the configuration in that file is default.

[settings.zip](https://github.com/PTMagicians/PTMagic/files/6757881/settings.zip)
