### ISSUE TITLE
Memory leak in web page

### ISSUE THREAD

**Issue by djbadders** [PTMagicians/PTMagic#31]
If you leave the PT Magic page up in Chrome for several hours it will eventually crash the Chrome tab due to lack of memory. Looks like we have a memory leak.

**Comment by HojouFotytu** [comment]
Which page, dashboard?   Can you reproduce this or did it happen once?   Did you confirm with chrome task manager and performance timeline?

**Comment by djbadders** [comment]
Main dashboard, reproducible if you leave it for several hours. Chrome reports out of memory and then the tab crashes. Haven't profiled it yet.
