### ISSUE TITLE
404 Error When Using PT 2.5.10

### ISSUE THREAD

**Issue by richpeck** [PTMagicians/PTMagic#318]
**Describe the bug**
If PTMagic (version 2.5.12) wants to update the config of PT (2.5.10) using the API, there is a 404 error, citing that it cannot access the "saveAll" API endpoint. 

**To Reproduce**
1. Set up PT (2.5.10) and PTMagic (2.5.12)
2. Set up a trigger and wait for the backend to update 
3. When the trigger occurs, PTMagic will attempt to update the settings in PT but will receive the following error:
` Saving Properties failed for setting 'default ': The remote server returned an error: (404) Not Found. System.Net.WebException The remote server returned an error: (404) Not Found.    at System.Net.HttpWebRequest.GetResponse()`
5. I have attached the screenshot of the error

**Expected behavior**
PTMagic should update ProfitTrailer's config settings.

**Screenshots**
![error](https://user-images.githubusercontent.com/1104431/165493820-6240c1c0-a7be-490d-9cf3-03a7a9eb0475.jpg)

**Desktop (please complete the following information):**
 - Ubuntu
 - Chrome
 - PT/PTMagic both running on PM2 without issue

**Additional context**
This problem seems to have started when we bumped the PT and PTMagic versions to the latest. I have managed to identify the error - which, I believe, is either going to be caused by an incorrect "default setting" variable name or an incorrect API endpoint URL: https://github.com/PTMagicians/PTMagic/blob/2a28c0382fe16510c11bcbd888a645d92f5bbc10/Core/ProfitTrailer/SettingsAPI.cs#L56

As there is no documentation for the ProfitTrailer API, I have no idea whether the endpoint is being correctly referenced or whether there is an issue with the integrity of the data payload being passed to it.

**Comment by HojouFotytu** [comment]
I just updated to 2.5.10 and I'm not getting this error on any of my bots, also on Ubuntu.

If you are running on the same server, are you using localhost as the address?

**Comment by richpeck** [comment]
We've tried it with the raw IP and same problem.

Because there is no API documentation for ProfitTrailer, I have not been able to determine if the issue is the endpoint URL or a malformed data payload. Specifically, the "default value" has almost 0 explanation inside PTMagic.

**Comment by HojouFotytu** [comment]
"Default setting name" is the name of the setting you are using in PT, that you want PTM to write to...

**Comment by richpeck** [comment]
![configs](https://user-images.githubusercontent.com/1104431/166413967-cff2c7bb-9e88-4572-917e-29cfcfdddc5d.jpg)

In our case, that would be "Bot_1"?

**Comment by HojouFotytu** [comment]
Yes, if that's the active config...
![image](https://user-images.githubusercontent.com/36724681/166414208-4a71174e-b6fc-4429-bd36-06cdc444c0ef.png)

**Comment by HojouFotytu** [comment]
I updated the wiki to be more clear on this...

https://github.com/PTMagicians/PTMagic/wiki/settings.general#profittrailerdefaultsettingname

**Comment by richpeck** [comment]
Thank you for the clarification.

Unfortunately, it's exactly the same error (404).

I tried it with the localhost and the actual IP. 

Again, because I'm not seeing any logs from ProfitTrailer, or have any documentation for the API, I don't know if it's missing the endpoint or is sending a malformed request: -
![market_1](https://user-images.githubusercontent.com/1104431/166415997-dab14a13-ebbd-478f-b09d-7df487f7e12c.jpg)

![market_0](https://user-images.githubusercontent.com/1104431/166416004-5eff1995-579f-42e3-adc5-c03c46be8cb0.jpg)

**Comment by HojouFotytu** [comment]
I'm not sure if this is the actual cause, but I just saw the same thing on my bots.

My initial suspicion is that PT isn't responding fast enough, and PTM's query is timing out, due to CPU usage.

When my PBL has too many coins, and I can see on my server that CPU is maxing out, PT doesn't respond and I get a 404.   

When i reduce the PBL via `DEFAULT_min_buy_volume` things work out fine.

**Comment by richpeck** [comment]
Thanks for the previous message. 

Unfortunately, the error is the same :(
![404_error](https://user-images.githubusercontent.com/1104431/168003140-719cc686-be08-418e-b170-b3ef76bfe6f9.jpg)

**Comment by HojouFotytu** [comment]
A bit more digging and I think I've found the problem.  PTMagic seems to be hitting a limit for the size of the settings it is posting to PT's API.

After going back through my PTMagic logs, I noticed that I get the error anytime I have a large number of single market settings -- causing the pairs file to be larger than normal.

Whenever the number of single market settings is significantly lower, there is no problem.

In the past I have run into issues with PT's file size limits -- i'm waiting to hear back from Elroy to double check that my suspicion is correct, and whether or not this limit can be increased. 

The short term solution seems to be to reduce the number of lines generated by SMS settings if possible.

**Comment by richpeck** [comment]
Thank you for the update!! I will check it out today, got to do some work this morning then will have a look. Thank you for your continued support on the matter.

**Comment by HojouFotytu** [comment]
After more testing I can confirm this is the problem.    According to Elroy, PT has a file size limit of 4mb.

If the limit was the number of lines PTM generated, I could add some code to notify the user -- but since PTM doesn't actually build a file, there isn't an easy way to check for this before attempting to post to the API.

**Comment by richpeck** [comment]
Thank you. I will have a play around - really appreciate your time and dedication to looking at this.
