### ISSUE TITLE
Deprecated FreeCurrencyConverterAPIKey 

### ISSUE THREAD

**Issue by netscaline** [PTMagicians/PTMagic#321]
Hello,
I was wondering if you have an issue with FreeCurrencyConverterAPIKey ?

1) in my logs i have the following error : Error: Error whilst calling http://free.currencyconverterapi.com/api/v5/convert?q=USD_EUR&compact=y&apiKey=xyxyxyxyxyxyxxy - {"status":400,"error":"Invalid Free API Key.

2) i've notice that it's calling api v5 but in emails from CurrencyConverter they give the following with api v7 https://free.currconv.com/api/v7/convert?q=USD_PHP&compact=ultra&apiKey=xyxyxxyxyyxyxy

=> do you know how to change or resolve that to continue use this service ?

Thanks in advance

**Comment by HojouFotytu** [comment]
The free service has been severely limited in functionality, and after some searching it seems most similar services require a monthly fee.

Until another option comes to light, support for this feature will be removed. 

An alternative option would be to allow the user to specify an exchange rate manually on the settings page, but this would lead to only rough estimates, which would have to be updated manually on a regular basis (daily?).

**Comment by HojouFotytu** [comment]
addressed in v2.7

live conversion rate is pulled from PT's API.
