### ISSUE TITLE
Ensure rebuy_timeout Values are an integer

### ISSUE THREAD

**Issue by HojouFotytu** [PTMagicians/PTMagic#42]
When using different OFFSETPERCENTs on rebuy_timeout values,  it is possible to end up with a value that is not an integer.   PTM should convert a decimal value to an integer before writing it to the PT settings.

For example, if someone has set a rebuy timeout of 5mins in their base settings, and they have a PTM setting that does an OFFSETPERCENT of -50%, it writes 2.5 to PT settings.  However,  PT only accepts integers for this value, so a real number is treated as null or zero when it encounters it in the settings files during runtime.

So currently, anyone using OFFSETPERCENT with rebuy timeouts has to be very careful and keep in mind the base values and possible combinations from global and sms settings, to make sure the result is always an integer.  this really restricts possible settings and real flexibility for this setting.

**Comment by nnation** [comment]
In a case where it has a decimal value and the systems should convert it to an integer value, should the systems take the ceiling or the floor value (or in other words, should it round up or round down) and store the integer value?

**Comment by JackTerok** [comment]
I would always round it mathematically correct.

**Comment by nnation** [comment]
I had a bit of challenge with this issue, I had to spend sometime understanding what and where is OFFSETPERCENTs. Had to use PT wiki and the code behind to help. I believe have screenshots of PTM web page would have helped to faster zone in on the problem area. 
![screenshot 2019-02-21 at 12 59 16 pm](https://user-images.githubusercontent.com/8162503/53191246-50b93080-35d9-11e9-96c3-7019abc0006c.png)
