### ISSUE TITLE
PTMagic Monitor 2.1.0 doesn't work for me

### ISSUE THREAD

**Issue by tr1plx** [PTMagicians/PTMagic#46]
Hi, I'm running two instances of Profittrailer 2.1.30 with PTMagic 2.0.6 on an Ubuntu-Server having Microsoft.NETCore.App/2.2.1 installed - that works just fine.

Yesterday I decided to upgrade to PT 2.2.0 with PTMagic 2.1.0, but I ran into some issues.
My bots running headless using pm2, so I checked the logs and there are no problems in there to find.
The WebUi of Profittrailer 2.2.0 is working just fine, but the PT-magic WebUi 2.1.0 is loading but it gets errors refreshing Data (Dashboard Ticker update and Ticker update failed). So I checked the logs again but I can't figure out any Problems so far. Everthing seems to work just fine, except the WebUI of PTMagic 2.1.0

Maybe there's an issue with the running Version Microsoft.NETCore.App/2.2.1 or thatelse can I troubleshoot ?

Thanks for your replys

**Comment by HojouFotytu** [comment]
Please use the discord for support.  Github issues is for bug reports and feature requests.
