### ISSUE TITLE
Adjustable start-up delay/options

### ISSUE THREAD

**Issue by Thndr** [PTMagicians/PTMagic#50]
On slower machines it may take Profit Trailer longer to start up than it does for PTMagic to start up and then cycle through all 20 connection attempts.
To resolve this issue when automatically starting up all the services on a machine I would like to suggest putting in an option to ensure that PTMagic successfully connects even if ProfitTrailer takes a while to load.

One suggestion is a long delay between batches of reconnection attempts. Where it tries X times then waits Y minutes or more before trying X more times.
Another suggestion would be to be able to set how many attempts it tries, and the delay between attempts.

In the end if the user can adjust it to what works for their system then I believe that should prevent this sort of issue in the future.

**Comment by djbadders** [comment]
We have added a retry feature that will keep looking for Profit trailer indefinitely but gradually back off the retry period to a maximum period of 15 mins. This will ensure PTM can find Profit Trailer without thrashing the machine.
