### ISSUE TITLE
Free.currencyconverterapi.com requires API Key

### ISSUE THREAD

**Issue by HojouFotytu** [PTMagicians/PTMagic#53]
The currency conversion service being used by PTM now requires an API key.

https://free.currencyconverterapi.com/

With a key, it allows 100 calls per hour, so it will still work, once the functionality is added to allow a user to provide they personal API key.
![image](https://user-images.githubusercontent.com/36724681/52826212-4abbdf00-3103-11e9-9a6e-c58d9c94a894.png)

**Comment by Feddok** [comment]
This also happens wiyh my ptm.
How can it be fixed?

**Comment by HojouFotytu** [comment]
A fix is coming with the next update @Feddok

**Comment by Feddok** [comment]
Hello,
Thanks for the reply.
After installing the updaten, i get some kind of error.

Unhandled Exception: System.NullReferenceException: Object reference not
set to an instance of an object.
   at Core.Main.PTMagic.RunConfigurationChecks() in G:\PTM Dev Bot\PTMagic
Github Clone\PTMagic\Core\Main\PTMagic.cs:line 661
   at Core.Main.PTMagic.StartProcess() in G:\PTM Dev Bot\PTMagic Github
Clone\PTMagic\Core\Main\PTMagic.cs:line 538
   at PTMagic.Program.Main(String[] args) in G:\PTM Dev Bot\PTMagic Github
Clone\PTMagic\PTMagic\Program.cs:line 24

C:\Users\Eigenaar\Desktop\Profit trailer\PTMagi\PTMagic 2.0.3\PTMagic>pause
Press any key to continue . . .

For me it looks like it is trying to connect to a G drive which i don't
have.
What could it be?

Best regards
Feddo



Op zo 17 feb. 2019 om 06:02 schreef HojouFotytu <notifications@github.com>:

**Comment by HojouFotytu** [comment]
Please read the notes and make sure you have added the new line to you setting.general file.
