### ISSUE TITLE
Settings changes not updating

### ISSUE THREAD

**Issue by HojouFotytu** [PTMagicians/PTMagic#55]
When changing the settings in the _presets folder, PTM has a check for changes since the last run to push any changes to the PT API, but it isn't functioning correctly.

Currently, changes to the settings files in the _presets folder are only pushed if the global settings change.

**Comment by nnation** [comment]
Hi @HojouFotytu Can you provide any supporting screenshot that you think might be helpful?

**Comment by HojouFotytu** [comment]
Not really.  there isn't anything to screenshot...

**Comment by djbadders** [comment]
I have added a file watcher that will run the main processing when it detects file changes in the _preset folder structure.

**Comment by djbadders** [comment]
Issue only resolved on Windows; Unix is not seeing the file changes

**Comment by djbadders** [comment]
Deployment issue on Unix, actually all is working fine in the retest
