### ISSUE TITLE
Single Market settings get stuck until the next market setting change if defined in the preset file as well

### ISSUE THREAD

**Issue by djbadders** [PTMagicians/PTMagic#90]
Single Market settings get stuck until the next market setting change if defined in the preset file as well. For instance if you have SOM defined at in your preset file for specific pairs and then the Single Market Settings  override this then the issue will occur. 

The issue is caused by PT depuing and optimising the config when saved. PTM is writing the SMS market config at the end of the config as designed but PT optimises the duplicate entries in the config file and merges the SMS setting changes in at the first instance of the settings line, which in this case in now above the SMS settings block. As the setting value is outside of the SMS settings block on the next run of PTM the setting is not changed and therefore sticks until PTM regens the whole config during a market condition change.

**Comment by HojouFotytu** [comment]
"PT optimises the duplicate entries in the config file and merges the SMS setting changes in at the first instance of the settings line,"   doesn't sound correct.  PT does not modify the settings files in any way, other than to delete blank lines.

If there are duplicate entries in the pair setting, even if they are exactly the same.  PT does not modify or delete these lines.  It will simply use the last one in the setting.

**Comment by djbadders** [comment]
Definitely a bug IMO as the design was not to leave SMS settings in play after the conditions cleared, and has caused me issues missing DCA steps. I debugged the SMS logic and the pairs file submitted to PT had the settings at the end in the SMS block as I expected but PT deduped them and put the last value in the position of the first occurrence of the setting, which is what causes the issue. I suspect this optimisation was introduced when PT went to v2.*.* with the introduction of the settings API, makes sense from PT point of view.

Several options exist for rectifying this, but the simplest is to read the preset files each time we generate the new config, rather than drawing on PT's copy. Will test this approach.

**Comment by HojouFotytu** [comment]
Sorry, I was wrong.  I just tested, and you are right:  the PT logic has changed.  

It is definitely removing duplicate instances of any parameter it finds, and placing the last instance in the position of the first instance encountered.

And I think you are also correct, that the only solution is to generate a new config any time there are any changes.

**Comment by HojouFotytu** [comment]
@djbadders 
After talking to Elroy I think i understand more clearly what is happening -- an object is being created by the API in the first instance with properties defining it's location in the settings, and then the second value is simply being assigned, while it still retains its initial location properties.

**Comment by djbadders** [comment]
@HojouFotytu thanks for checking that. I have implemented the fix of always regenerating the settings from the preset files and it seems to be working well. Expect a PR soon.
